import 'package:json_annotation/json_annotation.dart';

// part 'pantry_item_model.g.dart';
// Note: Generated file will be created after running: flutter pub run build_runner build

@JsonSerializable()
class PantryItemModel {
  final String? id;
  final String userId;
  final String category;
  final String name;
  final double weight;
  final double price;
  final String unit;
  final DateTime createdAt;
  final DateTime? updatedAt;

  PantryItemModel({
    this.id,
    required this.userId,
    required this.category,
    required this.name,
    required this.weight,
    required this.price,
    required this.unit,
    required this.createdAt,
    this.updatedAt,
  });

  // JSON serialization methods will be generated by build_runner
  factory PantryItemModel.fromJson(Map<String, dynamic> json) {
    return PantryItemModel(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      category: json['category'] as String,
      name: json['name'] as String,
      weight: (json['weight'] as num).toDouble(),
      price: (json['price'] as num).toDouble(),
      unit: json['unit'] as String,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() => {
        'user_id': userId,
        'category': category,
        'name': name,
        'weight': weight,
        'price': price,
        'unit': unit,
        'created_at': createdAt.toIso8601String(),
        'updated_at': updatedAt?.toIso8601String(),
      };

  PantryItemModel copyWith({
    String? id,
    String? userId,
    String? category,
    String? name,
    double? weight,
    double? price,
    String? unit,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return PantryItemModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      category: category ?? this.category,
      name: name ?? this.name,
      weight: weight ?? this.weight,
      price: price ?? this.price,
      unit: unit ?? this.unit,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}
