import 'package:json_annotation/json_annotation.dart';

// part 'planner_meal_model.g.dart';
// Note: Generated file will be created after running: flutter pub run build_runner build

@JsonSerializable()
class PlannerMealModel {
  final String? id;
  final String userId;
  final DateTime date;
  final String mealType; // Breakfast, Lunch, Dinner, Snack
  final String dishName;
  final String? recipeId;
  final DateTime createdAt;

  PlannerMealModel({
    this.id,
    required this.userId,
    required this.date,
    required this.mealType,
    required this.dishName,
    this.recipeId,
    required this.createdAt,
  });

  // JSON serialization methods will be generated by build_runner
  factory PlannerMealModel.fromJson(Map<String, dynamic> json) {
    return PlannerMealModel(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      date: DateTime.parse(json['date'] as String),
      mealType: json['meal_type'] as String,
      dishName: json['dish_name'] as String,
      recipeId: json['recipe_id'] as String?,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    final json = {
      'user_id': userId,
      'date': date.toIso8601String(),
      'meal_type': mealType,
      'dish_name': dishName,
      'recipe_id': recipeId,
      'created_at': createdAt.toIso8601String(),
    };
    if (id != null) {
      json['id'] = id;
    }
    return json;
  }

  PlannerMealModel copyWith({
    String? id,
    String? userId,
    DateTime? date,
    String? mealType,
    String? dishName,
    String? recipeId,
    DateTime? createdAt,
  }) {
    return PlannerMealModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      date: date ?? this.date,
      mealType: mealType ?? this.mealType,
      dishName: dishName ?? this.dishName,
      recipeId: recipeId ?? this.recipeId,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
