import 'package:json_annotation/json_annotation.dart';

// part 'recipe_model.g.dart';
// Note: Generated file will be created after running: flutter pub run build_runner build

@JsonSerializable()
class RecipeModel {
  @JsonKey(name: 'idMeal')
  final String id;

  @JsonKey(name: 'strMeal')
  final String name;

  @JsonKey(name: 'strCategory')
  final String? category;

  @JsonKey(name: 'strArea')
  final String? area;

  @JsonKey(name: 'strInstructions')
  final String? instructions;

  @JsonKey(name: 'strMealThumb')
  final String? imageUrl;

  @JsonKey(name: 'strTags')
  final String? tags;

  @JsonKey(name: 'strYoutube')
  final String? youtubeUrl;

  // Ingredients and measurements (stored as ingredients list)
  final List<String> ingredients;
  final List<String> measurements;

  RecipeModel({
    required this.id,
    required this.name,
    this.category,
    this.area,
    this.instructions,
    this.imageUrl,
    this.tags,
    this.youtubeUrl,
    required this.ingredients,
    required this.measurements,
  });

  // JSON serialization methods will be generated by build_runner
  factory RecipeModel.fromJson(Map<String, dynamic> json) {
    final ingredients = <String>[];
    final measurements = <String>[];

    for (int i = 1; i <= 20; i++) {
      final ingredient = json['strIngredient$i'] as String?;
      final measurement = json['strMeasure$i'] as String?;
      if (ingredient != null && ingredient.isNotEmpty) {
        ingredients.add(ingredient);
        measurements.add(measurement ?? '');
      }
    }

    return RecipeModel(
      id: json['idMeal'] as String,
      name: json['strMeal'] as String,
      imageUrl: json['strMealThumb'] as String?,
      category: json['strCategory'] as String?,
      area: json['strArea'] as String?,
      instructions: json['strInstructions'] as String?,
      tags: json['strTags'] as String?,
      youtubeUrl: json['strYoutube'] as String?,
      ingredients: ingredients,
      measurements: measurements,
    );
  }

  Map<String, dynamic> toJson() => {
        'idMeal': id,
        'strMeal': name,
        'strMealThumb': imageUrl,
        'strCategory': category,
        'strArea': area,
        'strInstructions': instructions,
        'strTags': tags,
        'strYoutube': youtubeUrl,
      };

  // Helper method to get ingredient-measurement pairs
  List<MapEntry<String, String>> getIngredientPairs() {
    final pairs = <MapEntry<String, String>>[];
    for (int i = 0; i < ingredients.length; i++) {
      if (ingredients[i].isNotEmpty &&
          measurements.length > i &&
          measurements[i].isNotEmpty) {
        pairs.add(MapEntry(ingredients[i], measurements[i]));
      }
    }
    return pairs;
  }
}
