import 'package:json_annotation/json_annotation.dart';

// part 'usage_log_model.g.dart';
// Note: Generated file will be created after running: flutter pub run build_runner build

@JsonSerializable()
class UsageLogModel {
  final String? id;
  final String userId;
  final String itemId;
  final String itemName;
  final String category;
  final double weightUsed;
  final double priceUsed;
  final String unit;
  final DateTime usedAt;

  UsageLogModel({
    this.id,
    required this.userId,
    required this.itemId,
    required this.itemName,
    required this.category,
    required this.weightUsed,
    required this.priceUsed,
    required this.unit,
    required this.usedAt,
  });

  // JSON serialization methods will be generated by build_runner
  factory UsageLogModel.fromJson(Map<String, dynamic> json) {
    return UsageLogModel(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      itemId: json['item_id'] as String,
      itemName: json['item_name'] as String,
      category: json['category'] as String,
      weightUsed: (json['weight_used'] as num).toDouble(),
      priceUsed: (json['price_used'] as num).toDouble(),
      unit: json['unit'] as String,
      usedAt: json['used_at'] != null
          ? DateTime.parse(json['used_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() => {
        'user_id': userId,
        'item_id': itemId,
        'item_name': itemName,
        'category': category,
        'weight_used': weightUsed,
        'price_used': priceUsed,
        'unit': unit,
        'used_at': usedAt.toIso8601String(),
      };

  UsageLogModel copyWith({
    String? id,
    String? userId,
    String? itemId,
    String? itemName,
    String? category,
    double? weightUsed,
    double? priceUsed,
    String? unit,
    DateTime? usedAt,
  }) {
    return UsageLogModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      itemId: itemId ?? this.itemId,
      itemName: itemName ?? this.itemName,
      category: category ?? this.category,
      weightUsed: weightUsed ?? this.weightUsed,
      priceUsed: priceUsed ?? this.priceUsed,
      unit: unit ?? this.unit,
      usedAt: usedAt ?? this.usedAt,
    );
  }
}
